# Generated by Django 6.0.4 on 2026-04-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='codename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ward',
            name='codename',
            field=models.CharField(max_length=100),
        ),
    ]
